### ISSUE TITLE
Is the result of this method on KITTI-Raw based on stereo cameras?

### ISSUE THREAD

**Issue by pmj110119** [Brummi/BehindTheScenes#14]
Is the result of this method on KITTI-Raw based on stereo cameras? I would like to know if there is still a considerable performance with only a monocular camera or surrounding cameras.

**Comment by Brummi** [comment]
Yes, the results on KITTI Raw are with a model that was trained using both mono and stereo cameras.
I haven't tested mono only models, but I assume that the difference would be similar to the difference between Monodepth2 Mono and Monodepth2 Mono+Stereo.

**Comment by pmj110119** [comment]
Thanks for response!

In your experiments, you have outdoor+stereo (KITTI) and indoor+mono (RealEstate10K) settings. I am very curious about how this method would work in outdoor+mono (like nuscenes and waymo) setting where the camera perspective is relatively fixed and limited. 

I see that there is waymo-related code in this repo. Do you have any experimental results or some empirical insights?

**Comment by Brummi** [comment]
Hi!
sorry for the late reply!

Outdoor mono can be trained and will give you good depth results. However, with mono you get very little supervision for occluded regions (as can be seen in figure 4 in the paper). 

Regarding waymo: I did a few initial experiments and left the code in so that other people could adapt the code more easily.

Insights:
- The waymo camera quality is quite bad and there are a lot of disturbances, like rain, lensflare etc. Also, the exposure times vary which is not ideal for losses based on photometric consistency. Furthermore Waymo has a lot of moving objects, which leads to cars often not being predicted correctly. I am sure that you could get it to work with a few tweaks, but I didnt investigate further due to time constraints.

If you make any progress or have any extra questions, let me know! :D
